# Site settings
title: Colin Trent
email: trentcs@gmail.com
description: "Colin Trent's Homepage"
baseurl: ""
url: "http://trentcs.github.io"
twitter_username: TrentColin
github_username:  trentcs

# Build settings
markdown: kramdown
permalink: pretty
